"""Utility modules for BaoIAD."""
from baoiad.utils.compat import ensure_legacy_imgaug_compat, patch_numpy_sctypes  # noqa: F401
from baoiad.utils.image import save_tensor_image  # noqa: F401
from baoiad.utils.resad_official import (  # noqa: F401
    build_official_namespace,
    ensure_visa_split_csv,
    ensure_resad_few_shot_dir,
    get_reference_feature_class_names,
    get_setting_test_dataset,
    load_official_main,
    patch_official_dataloader_num_workers,
    patch_official_train_reference_tensor_cache,
    patch_timm_legacy_imports,
    prepare_reference_features,
    prepare_official_resad_import,
    validate_reference_feature_dir,
    validate_official_inputs,
)
from baoiad.utils.score_utils import minmax_normalize, normalize_class_name, safe_l2_normalize  # noqa: F401
from baoiad.utils.univad_assets import (  # noqa: F401
    assign_fine_to_coarse_torch,
    compose_labeled_mask,
    decompose_image_path,
    heat_mask_path_candidates,
    mask_path_candidates,
    relative_data_path,
    split_masks_from_one_mask,
    split_masks_from_one_mask_torch,
    split_masks_from_one_mask_with_bg,
    train_features_path_candidates,
)

__all__ = [
    'build_official_namespace',
    'assign_fine_to_coarse_torch',
    'compose_labeled_mask',
    'decompose_image_path',
    'ensure_legacy_imgaug_compat',
    'ensure_visa_split_csv',
    'ensure_resad_few_shot_dir',
    'get_reference_feature_class_names',
    'get_setting_test_dataset',
    'heat_mask_path_candidates',
    'load_official_main',
    'mask_path_candidates',
    'patch_official_dataloader_num_workers',
    'patch_official_train_reference_tensor_cache',
    'patch_numpy_sctypes',
    'patch_timm_legacy_imports',
    'prepare_reference_features',
    'prepare_official_resad_import',
    'relative_data_path',
    'minmax_normalize',
    'normalize_class_name',
    'safe_l2_normalize',
    'save_tensor_image',
    'split_masks_from_one_mask',
    'split_masks_from_one_mask_torch',
    'split_masks_from_one_mask_with_bg',
    'train_features_path_candidates',
    'validate_reference_feature_dir',
    'validate_official_inputs',
]
